// apps/admin-ui/src/app/login/page.tsx
'use client';

import { useState, FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import Script from 'next/script';
import { setToken } from '../../lib/auth';

declare global {
  interface Window {
    google?: {
      accounts: {
        id: {
          initialize: (cfg: { client_id: string; callback: (r: { credential: string }) => void }) => void;
          renderButton: (el: HTMLElement, cfg: object) => void;
        };
      };
    };
  }
}

export default function LoginPage() {
  const router = useRouter();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  function onGoogleLoad() {
    window.google?.accounts.id.initialize({
      client_id: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID ?? '',
      callback: async ({ credential }) => {
        setLoading(true);
        setError(null);
        try {
          const res = await fetch('/api/auth/google', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ idToken: credential }),
          });
          if (!res.ok) {
            const data = await res.json().catch(() => ({}));
            setError(res.status === 403 ? 'Access denied: not an authorized admin.' : data.message ?? 'Login failed.');
            return;
          }
          const { accessToken } = await res.json();
          setToken(accessToken);
          router.push('/');
        } finally {
          setLoading(false);
        }
      },
    });
    const btn = document.getElementById('google-btn');
    if (btn) {
      window.google?.accounts.id.renderButton(btn, { theme: 'outline', size: 'large', width: 320 });
    }
  }

  async function handleEmailLogin(e: FormEvent) {
    e.preventDefault();
    setLoading(true);
    setError(null);
    try {
      const res = await fetch('/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, password }),
      });
      if (!res.ok) {
        setError(res.status === 403 ? 'Access denied: not an authorized admin.' : 'Invalid email or password.');
        return;
      }
      const { accessToken } = await res.json();
      setToken(accessToken);
      router.push('/');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center">
      <Script src="https://accounts.google.com/gsi/client" onLoad={onGoogleLoad} />
      <div className="bg-white rounded-xl border border-gray-200 p-8 w-full max-w-sm space-y-6">
        <h1 className="text-xl font-semibold text-gray-900 text-center">Admin Sign In</h1>

        {error && (
          <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
            {error}
          </div>
        )}

        <div id="google-btn" className="flex justify-center" />

        <div className="flex items-center gap-3">
          <div className="flex-1 h-px bg-gray-200" />
          <span className="text-xs text-gray-400">or</span>
          <div className="flex-1 h-px bg-gray-200" />
        </div>

        <form onSubmit={handleEmailLogin} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Email</label>
            <input
              type="email"
              required
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Password</label>
            <input
              type="password"
              required
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>
          <button
            type="submit"
            disabled={loading}
            className="w-full rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50"
          >
            {loading ? 'Signing in…' : 'Sign in'}
          </button>
        </form>
      </div>
    </div>
  );
}

// apps/ui-angular/src/app/auth/login/login.component.ts
import { Component, ElementRef, NgZone, OnInit, ViewChild, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../auth.service';
import { environment } from '../../../environments/environment';

declare const google: any;

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [ReactiveFormsModule, RouterModule],
  templateUrl: './login.component.html',
})
export class LoginComponent implements OnInit {
  @ViewChild('googleBtn', { static: true }) googleBtnEl!: ElementRef;

  private fb = inject(FormBuilder);
  private auth = inject(AuthService);
  private router = inject(Router);
  private ngZone = inject(NgZone);

  form = this.fb.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', Validators.required],
  });
  readonly loading = signal(false);
  readonly error = signal('');
  readonly hidePassword = signal(true);

  toggleHidePassword() { this.hidePassword.update(v => !v); }

  ngOnInit() {
    if (typeof google !== 'undefined' && environment.googleClientId) {
      google.accounts.id.initialize({
        client_id: environment.googleClientId,
        callback: (response: { credential: string }) => {
          this.ngZone.run(() => this.handleGoogleCredential(response.credential));
        },
      });
      google.accounts.id.renderButton(this.googleBtnEl.nativeElement, {
        theme: 'outline',
        size: 'large',
        width: '100%',
        text: 'signin_with',
      });
    }
  }

  submit() {
    if (this.form.invalid) return;
    this.loading.set(true);
    this.error.set('');
    this.auth.login(this.form.value as { email: string; password: string }).subscribe({
      next: () => this.router.navigate(['/profile']),
      error: (err) => {
        this.error.set(err.status === 401 ? 'Invalid email or password.' : 'Login failed. Please try again.');
        this.loading.set(false);
      },
    });
  }

  private handleGoogleCredential(credential: string) {
    this.loading.set(true);
    this.error.set('');
    this.auth.googleLogin(credential).subscribe({
      next: () => this.router.navigate(['/profile']),
      error: () => {
        this.error.set('Google sign-in failed. Please try again.');
        this.loading.set(false);
      },
    });
  }
}

<div class="flex justify-center items-center min-h-screen">
  <div class="w-full max-w-sm bg-white dark:bg-gray-800 rounded-2xl shadow-lg p-8 transition-colors">
    <h1 class="text-2xl font-bold text-gray-800 dark:text-white">Sign In</h1>
    <p class="text-sm text-gray-500 dark:text-gray-400 mt-1">Welcome back to AI CV Maker</p>

    <form [formGroup]="form" (ngSubmit)="submit()" class="flex flex-col gap-4 mt-6">
      <div class="flex flex-col gap-1">
        <label class="text-sm font-medium text-gray-700 dark:text-gray-300">Email</label>
        <input type="email" formControlName="email" autocomplete="email" placeholder="you@example.com"
          class="border border-gray-300 dark:border-gray-600 rounded-lg px-3 py-2 text-sm bg-white dark:bg-gray-700 text-gray-900 dark:text-white placeholder-gray-400 dark:placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition" />
        @if (form.get('email')?.hasError('required') && form.get('email')?.touched) {
          <span class="text-xs text-red-500">Email is required</span>
        } @else if (form.get('email')?.hasError('email') && form.get('email')?.touched) {
          <span class="text-xs text-red-500">Enter a valid email</span>
        }
      </div>

      <div class="flex flex-col gap-1">
        <label class="text-sm font-medium text-gray-700 dark:text-gray-300">Password</label>
        <div class="relative">
          <input [type]="hidePassword() ? 'password' : 'text'" formControlName="password"
            autocomplete="current-password" placeholder="••••••••"
            class="w-full border border-gray-300 dark:border-gray-600 rounded-lg px-3 py-2 pr-10 text-sm bg-white dark:bg-gray-700 text-gray-900 dark:text-white placeholder-gray-400 dark:placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition" />
          <button type="button" (click)="toggleHidePassword()"
            class="absolute right-2.5 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 dark:text-gray-500 dark:hover:text-gray-300 bg-transparent border-0 p-0 cursor-pointer">
            <span class="material-icons text-[18px]">{{ hidePassword() ? 'visibility_off' : 'visibility' }}</span>
          </button>
        </div>
        @if (form.get('password')?.hasError('required') && form.get('password')?.touched) {
          <span class="text-xs text-red-500">Password is required</span>
        }
      </div>

      @if (error()) {
        <p class="text-sm text-red-500">{{ error() }}</p>
      }

      <button type="submit" [disabled]="loading()"
        class="bg-blue-600 hover:bg-blue-700 disabled:opacity-50 text-white font-medium rounded-lg py-2.5 text-sm flex items-center justify-center gap-2 transition-colors cursor-pointer border-0">
        @if (loading()) {
          <span class="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></span>
        } @else {
          Sign In
        }
      </button>
    </form>

    <div class="flex items-center gap-3 my-5">
      <div class="flex-1 h-px bg-gray-200 dark:bg-gray-600"></div>
      <span class="text-xs text-gray-400 dark:text-gray-500">or</span>
      <div class="flex-1 h-px bg-gray-200 dark:bg-gray-600"></div>
    </div>

    <div #googleBtn class="google-btn-container flex justify-center min-h-[44px]"></div>

    <p class="text-sm text-center text-gray-600 dark:text-gray-300 mt-5">
      Don't have an account?
      <a routerLink="/auth/register" class="text-blue-600 dark:text-blue-400 font-medium hover:underline">Register</a>
    </p>
  </div>
</div>
