// apps/ui-angular/src/app/shared/components/profile-preview/profile-preview.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';
import { Profile } from '../../models/profile.model';

@Component({
  selector: 'app-profile-preview',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './profile-preview.component.html',
})
export class ProfilePreviewComponent {
  readonly profile = input<Profile | null>(null);
  readonly loading = input(false);
}

@if (loading()) {
  <div class="flex items-center justify-center h-40">
    <span class="w-7 h-7 border-2 border-blue-200 dark:border-blue-900 border-t-blue-600 rounded-full animate-spin"></span>
  </div>
} @else if (profile()) {
  <div class="p-5">
    <div>

      <!-- Header -->
      <div class="pb-5 mb-5 border-b-2 border-gray-200 dark:border-gray-600">
        <h1 class="text-2xl font-bold text-gray-900 dark:text-white tracking-tight">{{ profile()!.fullName }}</h1>
        <p class="text-base text-indigo-600 dark:text-indigo-400 mt-1 font-medium">{{ profile()!.title }}</p>
        @if (profile()!.location) {
          <p class="flex items-center gap-1.5 text-xs text-gray-500 dark:text-gray-400 mt-1">
            <span class="material-icons text-[14px]">place</span>{{ profile()!.location }}
          </p>
        }
        @if (profile()!.contacts?.email || profile()!.contacts?.phone) {
          <div class="flex flex-wrap gap-x-4 gap-y-1 mt-2">
            @if (profile()!.contacts?.email) {
              <span class="flex items-center gap-1.5 text-xs text-gray-500 dark:text-gray-400">
                <span class="material-icons text-[14px]">email</span>{{ profile()!.contacts!.email }}
              </span>
            }
            @if (profile()!.contacts?.phone) {
              <span class="flex items-center gap-1.5 text-xs text-gray-500 dark:text-gray-400">
                <span class="material-icons text-[14px]">phone</span>{{ profile()!.contacts!.phone }}
              </span>
            }
          </div>
        }
      </div>

      <!-- Summary -->
      @if (profile()!.overview) {
        <section class="mb-6">
          <h2 class="text-[10px] font-bold text-gray-400 dark:text-gray-500 uppercase tracking-[0.15em] mb-2">Summary</h2>
          <p class="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">{{ profile()!.overview }}</p>
        </section>
      }

      <!-- Work Experience -->
      @if (profile()!.workExperiences?.length) {
        <section class="mb-6">
          <h2 class="text-[10px] font-bold text-gray-400 dark:text-gray-500 uppercase tracking-[0.15em] mb-3">Experience</h2>
          <div class="space-y-4">
            @for (job of profile()!.workExperiences; track $index) {
              <div>
                <div class="flex items-start justify-between gap-3">
                  <div>
                    <h3 class="text-sm font-bold text-gray-900 dark:text-white">{{ job.role }}</h3>
                    <p class="text-sm text-gray-500 dark:text-gray-400 mt-0.5">{{ job.company }}</p>
                  </div>
                  <span class="text-xs text-gray-400 dark:text-gray-500 whitespace-nowrap pt-0.5">
                    {{ job.startDate }} – {{ job.endDate || 'Present' }}
                  </span>
                </div>
                @if (job.description) {
                  <p class="text-xs text-gray-600 dark:text-gray-400 mt-2 leading-relaxed">{{ job.description }}</p>
                }
              </div>
            }
          </div>
        </section>
      }

      <!-- Education -->
      @if (profile()!.educations?.length) {
        <section class="mb-6">
          <h2 class="text-[10px] font-bold text-gray-400 dark:text-gray-500 uppercase tracking-[0.15em] mb-3">Education</h2>
          <div class="space-y-3">
            @for (edu of profile()!.educations; track $index) {
              <div class="flex items-start justify-between gap-3">
                <div>
                  <h3 class="text-sm font-bold text-gray-900 dark:text-white">{{ edu.degree }}{{ edu.field ? ' in ' + edu.field : '' }}</h3>
                  <p class="text-sm text-gray-500 dark:text-gray-400 mt-0.5">{{ edu.institution }}</p>
                </div>
                <span class="text-xs text-gray-400 dark:text-gray-500 whitespace-nowrap pt-0.5">
                  {{ edu.startYear }} – {{ edu.endYear || 'Present' }}
                </span>
              </div>
            }
          </div>
        </section>
      }

      <!-- Skills -->
      @if (profile()!.skills?.length) {
        <section>
          <h2 class="text-[10px] font-bold text-gray-400 dark:text-gray-500 uppercase tracking-[0.15em] mb-3">Skills</h2>
          <div class="flex flex-wrap gap-2">
            @for (skill of profile()!.skills; track $index) {
              <span class="inline-flex items-center px-3 py-1 bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 text-xs rounded-full border border-gray-200 dark:border-gray-600">
                {{ skill.name }}
              </span>
            }
          </div>
        </section>
      }

      <!-- Empty state -->
      @if (!profile()!.overview && !profile()!.location && !profile()!.workExperiences?.length && !profile()!.educations?.length && !profile()!.skills?.length) {
        <div class="flex flex-col items-center text-center py-16">
          <span class="material-icons text-5xl text-gray-200 dark:text-gray-700">description</span>
          <p class="text-sm text-gray-500 dark:text-gray-400 mt-4">Your profile is empty.</p>
          <a routerLink="/profile" class="text-sm text-blue-600 dark:text-blue-400 hover:underline mt-1">Fill in your profile →</a>
        </div>
      }

    </div>
  </div>
} @else {
  <div class="flex flex-col items-center text-center py-16 px-4">
    <span class="material-icons text-5xl text-gray-200 dark:text-gray-700">person_off</span>
    <p class="text-sm text-gray-500 dark:text-gray-400 mt-4">Could not load profile.</p>
    <a routerLink="/profile" class="text-sm text-blue-600 dark:text-blue-400 hover:underline mt-1">Go to Profile →</a>
  </div>
}

// apps/ui-react/src/shared/components/ProfilePreview.tsx
import { Link } from 'react-router-dom';

import type { Profile } from '../models/profile.model';

type Props = {
  profile: Profile | null;
  loading?: boolean;
};

export function ProfilePreview({ profile, loading }: Props) {
  if (loading) {
    return (
      <div className="flex h-40 items-center justify-center">
        <span className="h-7 w-7 animate-spin rounded-full border-2 border-blue-200 border-t-blue-600 dark:border-blue-900" />
      </div>
    );
  }

  if (profile) {
    return (
      <div className="p-8">
        <div className="mx-auto max-w-2xl">
          <div className="mb-5 border-b-2 border-gray-200 pb-5 dark:border-gray-600">
            <h1 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
              {profile.fullName}
            </h1>
            <p className="mt-1 text-base font-medium text-indigo-600 dark:text-indigo-400">
              {profile.title}
            </p>
            {profile.location ? (
              <p className="mt-1 flex items-center gap-1.5 text-xs text-gray-500 dark:text-gray-400">
                <span className="material-icons text-[14px]">place</span>
                {profile.location}
              </p>
            ) : null}
            {(profile.contacts?.email || profile.contacts?.phone) && (
              <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1">
                {profile.contacts?.email && (
                  <span className="flex items-center gap-1.5 text-xs text-gray-500 dark:text-gray-400">
                    <span className="material-icons text-[14px]">email</span>
                    {profile.contacts.email}
                  </span>
                )}
                {profile.contacts?.phone && (
                  <span className="flex items-center gap-1.5 text-xs text-gray-500 dark:text-gray-400">
                    <span className="material-icons text-[14px]">phone</span>
                    {profile.contacts.phone}
                  </span>
                )}
              </div>
            )}
          </div>

          {profile.overview && (
            <section className="mb-6">
              <h2 className="mb-2 text-[10px] font-bold uppercase tracking-[0.15em] text-gray-400 dark:text-gray-500">
                Summary
              </h2>
              <p className="text-sm leading-relaxed text-gray-700 dark:text-gray-300">
                {profile.overview}
              </p>
            </section>
          )}

          {!!profile.workExperiences?.length && (
            <section className="mb-6">
              <h2 className="mb-3 text-[10px] font-bold uppercase tracking-[0.15em] text-gray-400 dark:text-gray-500">
                Experience
              </h2>
              <div className="space-y-4">
                {profile.workExperiences.map((job, i) => (
                  <div key={i}>
                    <div className="flex items-start justify-between gap-3">
                      <div>
                        <h3 className="text-sm font-bold text-gray-900 dark:text-white">
                          {job.role}
                        </h3>
                        <p className="mt-0.5 text-sm text-gray-500 dark:text-gray-400">
                          {job.company}
                        </p>
                      </div>
                      <span className="whitespace-nowrap pt-0.5 text-xs text-gray-400 dark:text-gray-500">
                        {job.startDate} – {job.endDate || 'Present'}
                      </span>
                    </div>
                    {job.description && (
                      <p className="mt-2 text-xs leading-relaxed text-gray-600 dark:text-gray-400">
                        {job.description}
                      </p>
                    )}
                  </div>
                ))}
              </div>
            </section>
          )}

          {!!profile.educations?.length && (
            <section className="mb-6">
              <h2 className="mb-3 text-[10px] font-bold uppercase tracking-[0.15em] text-gray-400 dark:text-gray-500">
                Education
              </h2>
              <div className="space-y-3">
                {profile.educations.map((edu, i) => (
                  <div key={i} className="flex items-start justify-between gap-3">
                    <div>
                      <h3 className="text-sm font-bold text-gray-900 dark:text-white">
                        {edu.degree}
                        {edu.field ? ` in ${edu.field}` : ''}
                      </h3>
                      <p className="mt-0.5 text-sm text-gray-500 dark:text-gray-400">
                        {edu.institution}
                      </p>
                    </div>
                    <span className="whitespace-nowrap pt-0.5 text-xs text-gray-400 dark:text-gray-500">
                      {edu.startYear} – {edu.endYear ?? 'Present'}
                    </span>
                  </div>
                ))}
              </div>
            </section>
          )}

          {!!profile.skills?.length && (
            <section>
              <h2 className="mb-3 text-[10px] font-bold uppercase tracking-[0.15em] text-gray-400 dark:text-gray-500">
                Skills
              </h2>
              <div className="flex flex-wrap gap-2">
                {profile.skills.map((skill, i) => (
                  <span
                    key={i}
                    className="inline-flex items-center rounded-full border border-gray-200 bg-gray-100 px-3 py-1 text-xs text-gray-700 dark:border-gray-600 dark:bg-gray-700 dark:text-gray-300"
                  >
                    {skill.name}
                  </span>
                ))}
              </div>
            </section>
          )}

          {!profile.overview &&
            !profile.location &&
            !profile.workExperiences?.length &&
            !profile.educations?.length &&
            !profile.skills?.length && (
              <div className="flex flex-col items-center py-16 text-center">
                <span className="material-icons text-5xl text-gray-200 dark:text-gray-700">
                  description
                </span>
                <p className="mt-4 text-sm text-gray-500 dark:text-gray-400">
                  Your profile is empty.
                </p>
                <Link
                  to="/profile"
                  className="mt-1 text-sm text-blue-600 hover:underline dark:text-blue-400"
                >
                  Fill in your profile →
                </Link>
              </div>
            )}
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col items-center px-4 py-16 text-center">
      <span className="material-icons text-5xl text-gray-200 dark:text-gray-700">
        person_off
      </span>
      <p className="mt-4 text-sm text-gray-500 dark:text-gray-400">
        Could not load profile.
      </p>
      <Link
        to="/profile"
        className="mt-1 text-sm text-blue-600 hover:underline dark:text-blue-400"
      >
        Go to Profile →
      </Link>
    </div>
  );
}
